### PR TITLE
add data to the LS_CSR

### PR DESCRIPTION
**Pull request by meyerzinn**
~right now, adding edges with data cannot be done in parallel. This could be fixed with the parallel hashmap.~

### CODE REVIEW

**Comment by patrickkenney9801** [comment]
have you added the pre-commit hooks via `make hooks`? or are you editing this as a submodule of gls?

**Comment by meyerzinn** [comment]
> have you added the pre-commit hooks via `make hooks`? or are you editing this as a submodule of gls?

Pre-commit hooks are passing for me.

**Comment by meyerzinn** [comment]
@AdityaAtulTewari this is ready for review.

@divija95 this should make LS_CSR useful for applications that associate data with vertices/edges.

**Comment by patrickkenney9801** [comment]
Looks good to me on the phmap front

**Review by tewaro — APPROVED** [review]

**Pull request merged**
